#line 2 "..\\..\\simulator\\flex_bison\\..\\mips_lexer.c"

#line 4 "..\\..\\simulator\\flex_bison\\..\\mips_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer mips_lexer__create_buffer
#define yy_delete_buffer mips_lexer__delete_buffer
#define yy_flex_debug mips_lexer__flex_debug
#define yy_init_buffer mips_lexer__init_buffer
#define yy_flush_buffer mips_lexer__flush_buffer
#define yy_load_buffer_state mips_lexer__load_buffer_state
#define yy_switch_to_buffer mips_lexer__switch_to_buffer
#define yyin mips_lexer_in
#define yyleng mips_lexer_leng
#define yylex mips_lexer_lex
#define yylineno mips_lexer_lineno
#define yyout mips_lexer_out
#define yyrestart mips_lexer_restart
#define yytext mips_lexer_text
#define yywrap mips_lexer_wrap
#define yyalloc mips_lexer_alloc
#define yyrealloc mips_lexer_realloc
#define yyfree mips_lexer_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE mips_lexer_restart(mips_lexer_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int mips_lexer_leng;

extern FILE *mips_lexer_in, *mips_lexer_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up mips_lexer_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up mips_lexer_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via mips_lexer_restart()), so that the user can continue scanning by
	 * just pointing mips_lexer_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when mips_lexer_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int mips_lexer_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow mips_lexer_wrap()'s to do buffer switches
 * instead of setting up a fresh mips_lexer_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void mips_lexer_restart (FILE *input_file  );
void mips_lexer__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE mips_lexer__create_buffer (FILE *file,int size  );
void mips_lexer__delete_buffer (YY_BUFFER_STATE b  );
void mips_lexer__flush_buffer (YY_BUFFER_STATE b  );
void mips_lexer_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void mips_lexer_pop_buffer_state (void );

static void mips_lexer_ensure_buffer_stack (void );
static void mips_lexer__load_buffer_state (void );
static void mips_lexer__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER mips_lexer__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE mips_lexer__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE mips_lexer__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE mips_lexer__scan_bytes (yyconst char *bytes,int len  );

void *mips_lexer_alloc (yy_size_t  );
void *mips_lexer_realloc (void *,yy_size_t  );
void mips_lexer_free (void *  );

#define yy_new_buffer mips_lexer__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        mips_lexer_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            mips_lexer__create_buffer(mips_lexer_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        mips_lexer_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            mips_lexer__create_buffer(mips_lexer_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define mips_lexer_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *mips_lexer_in = (FILE *) 0, *mips_lexer_out = (FILE *) 0;

typedef int yy_state_type;

extern int mips_lexer_lineno;

int mips_lexer_lineno = 1;

extern char *mips_lexer_text;
#define yytext_ptr mips_lexer_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up mips_lexer_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	mips_lexer_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[151] =
    {   0,
        0,    0,    0,    0,   80,   78,    1,   77,   78,   78,
       78,   78,   74,   74,   39,   39,   39,   37,   39,   39,
       39,   39,   79,    0,    2,   40,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   74,   74,    0,    0,    0,
        0,    0,    0,    0,    0,   39,   39,   39,   39,   39,
       20,   17,   39,   15,   39,   25,   22,   19,   39,   39,
       39,   16,   39,   40,   46,   47,   48,   49,   43,   72,
       70,   68,   69,   41,   73,   60,   61,   62,   63,   64,
       65,   66,   67,   71,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   44,   45,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   76,   12,   24,   31,   32,
       21,   18,   23,   11,   26,   28,   29,   33,   30,   13,
       39,   41,    0,   75,    0,    0,    7,    6,    0,    0,
        0,    0,   14,   27,   35,   34,   39,   42,    8,    4,
        0,    9,    3,   10,   36,   39,    5,   39,   38,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    6,    7,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,    1,    1,    1,
        1,    1,    1,    1,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   18,
        1,    1,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   28,   29,   30,   18,   31,
       32,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[44] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    3,    4,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[160] =
    {   0,
        0,    0,    0,    0,  190,  191,  191,  191,  186,   36,
      180,   60,  146,    0,    0,   32,   33,    0,   50,  154,
      150,   81,  191,  181,  191,    0,   58,  150,  149,   49,
      162,  116,  142,   69,  157,  138,    0,  136,  158,  145,
      145,  155,  149,  116,    0,    0,  125,  124,  111,  121,
      105,  104,  114,    0,   54,  113,    0,    0,   44,  109,
      118,    0,  101,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,    0,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  191,  191,  191,  191,  191,  101,    0,   98,   97,

       62,  101,  102,   81,   85,    0,   91,   90,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   64,    0,    0,
       94,  191,   82,    0,   90,   93,  191,  191,   90,   85,
       71,   84,    0,    0,   67,    0,   85,  191,  191,  191,
       73,  191,  191,  191,    0,   68,  191,   66,    0,  191,
      159,  163,   92,  166,   91,  169,   90,   60,   57
    } ;

static yyconst flex_int16_t yy_def[160] =
    {   0,
      150,    1,  151,  151,  150,  150,  150,  150,  152,  150,
      153,  150,  153,  153,  154,  154,  154,  154,  154,  154,
      154,  154,  150,  152,  150,  155,  150,  150,  150,  150,
      156,  150,  150,  150,  150,  153,  153,  150,  150,  150,
      150,  150,  150,  150,  157,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  158,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  159,  150,  150,

      150,  150,  150,  150,  150,  157,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  154,  154,  154,  154,  154,
      154,  150,  150,  159,  150,  150,  150,  150,  150,  150,
      150,  150,  154,  154,  154,  154,  154,  150,  150,  150,
      150,  150,  150,  150,  154,  154,  150,  154,  154,    0,
      150,  150,  150,  150,  150,  150,  150,  150,  150
    } ;

static yyconst flex_int16_t yy_nxt[235] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       15,   15,   15,   15,   15,   15,   15,   18,   15,   19,
       20,   21,   15,   15,   15,   22,   15,   15,   15,   15,
       15,   15,   15,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   47,   27,   49,   72,   73,  124,   28,
       29,  122,   48,   50,   30,   65,   66,   67,   68,   51,
       31,   32,   33,  117,   34,   52,   95,   96,   35,   38,
      118,   39,   40,  127,   41,   42,  114,   53,  115,   54,
      135,  106,   64,   37,   69,  149,   43,  148,  128,   44,

       57,  136,  147,  146,  145,  144,   58,  143,  142,  141,
       59,  140,  139,  138,  137,   60,  134,  133,   61,  132,
       62,  131,   63,   76,   77,   78,   79,   80,   81,   82,
       83,  130,  129,  126,  125,  123,  121,  120,  119,  116,
      113,  112,  111,  110,  109,  108,  107,  105,   84,   85,
       86,   87,   88,   89,   90,   91,   92,   93,   94,   23,
       23,   23,   23,   24,   24,   24,   24,   46,   46,   46,
       74,  104,   74,  103,  102,  101,  100,   99,   98,   97,
       75,   71,   70,   25,   56,   55,   45,   36,   25,  150,
        5,  150,  150,  150,  150,  150,  150,  150,  150,  150,

      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150
    } ;

static yyconst flex_int16_t yy_chk[235] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   16,   10,   17,   30,   30,  159,   10,
       10,  158,   16,   17,   10,   27,   27,   27,   27,   19,
       10,   10,   10,   59,   10,   19,   34,   34,   10,   12,
       59,   12,   12,  101,   12,   12,   55,   19,   55,   19,
      118,  157,  155,  153,   27,  148,   12,  146,  101,   12,

       22,  118,  141,  137,  135,  132,   22,  131,  130,  129,
       22,  126,  125,  123,  121,   22,  108,  107,   22,  105,
       22,  104,   22,   32,   32,   32,   32,   32,   32,   32,
       32,  103,  102,  100,   99,   97,   63,   61,   60,   56,
       53,   52,   51,   50,   49,   48,   47,   44,   32,   33,
       33,   33,   33,   33,   33,   33,   33,   33,   33,  151,
      151,  151,  151,  152,  152,  152,  152,  154,  154,  154,
      156,   43,  156,   42,   41,   40,   39,   38,   36,   35,
       31,   29,   28,   24,   21,   20,   13,   11,    9,    5,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,

      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int mips_lexer__flex_debug;
int mips_lexer__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *mips_lexer_text;
#line 1 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
#define YY_NO_UNISTD_H 1
#line 6 "..\\..\\simulator\\flex_bison\\mips_lexer.l"

#include "instructions.h"
#include "register_file.h"
#include "mips_parser_tokens.h"

#define YY_USER_ACTION UpdateLocation(yylloc_param);

#define RETURN_INSTRUCTION(INSTR_TYPE, TOKEN) \
	yylval->instr_type = INSTR_TYPE; \
	return TOKEN;

#define RETURN_REGISTER(REG_NR) \
	yylval->integer = REG_NR; \
	return REGISTER;

static void UpdateLocation(YYLTYPE* location)
{
	// First make the previous last_line and _column the new first_ dittos
	location->first_line = location->last_line;
	location->first_column = location->last_column;
	
	// Update the new first_line and _column
	{
		const char* start, * end;
		for (start = mips_lexer_text, end = strchr(mips_lexer_text, '\n'); end != 0; 
			start = end + 1, end = strchr(start, '\n'))
		{
			++location->last_line;
			location->last_column = 1;
		}
		location->last_column += mips_lexer_text + mips_lexer_leng - start;
	}
}


#line 610 "..\\..\\simulator\\flex_bison\\..\\mips_lexer.c"

#define INITIAL 0
#define READ_EOF_ONCE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int mips_lexer_lex_destroy (void );

int mips_lexer_get_debug (void );

void mips_lexer_set_debug (int debug_flag  );

YY_EXTRA_TYPE mips_lexer_get_extra (void );

void mips_lexer_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *mips_lexer_get_in (void );

void mips_lexer_set_in  (FILE * in_str  );

FILE *mips_lexer_get_out (void );

void mips_lexer_set_out  (FILE * out_str  );

int mips_lexer_get_leng (void );

char *mips_lexer_get_text (void );

int mips_lexer_get_lineno (void );

void mips_lexer_set_lineno (int line_number  );

YYSTYPE * mips_lexer_get_lval (void );

void mips_lexer_set_lval (YYSTYPE * yylval_param  );

       YYLTYPE *mips_lexer_get_lloc (void );
    
        void mips_lexer_set_lloc (YYLTYPE * yylloc_param  );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int mips_lexer_wrap (void );
#else
extern int mips_lexer_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( mips_lexer_text, mips_lexer_leng, 1, mips_lexer_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( mips_lexer_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( mips_lexer_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, mips_lexer_in))==0 && ferror(mips_lexer_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(mips_lexer_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int mips_lexer_lex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param );

#define YY_DECL int mips_lexer_lex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param )
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after mips_lexer_text and mips_lexer_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
        YYSTYPE * yylval;
    
        YYLTYPE * yylloc;
    
#line 44 "..\\..\\simulator\\flex_bison\\mips_lexer.l"


#line 810 "..\\..\\simulator\\flex_bison\\..\\mips_lexer.c"

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! mips_lexer_in )
			mips_lexer_in = stdin;

		if ( ! mips_lexer_out )
			mips_lexer_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			mips_lexer_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				mips_lexer__create_buffer(mips_lexer_in,YY_BUF_SIZE );
		}

		mips_lexer__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of mips_lexer_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 151 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 191 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ /* Throw away spaces and tabs */ }
	YY_BREAK
case 2:
*yy_cp = (yy_hold_char); /* undo effects of setting up mips_lexer_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up mips_lexer_text again */
YY_RULE_SETUP
#line 48 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ /* Comment */ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 50 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return TEXT_DIR; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 51 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return DATA_DIR; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 52 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return GLOBL_DIR; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 53 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return ENT_DIR; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 54 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return END_DIR; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 56 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return BYTE_DIR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 57 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return HALF_DIR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 58 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return WORD_DIR; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 60 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(NOP, EMPTY_INSTR) }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 62 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(ADD, RRR_INSTR) }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 63 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SUB, RRR_INSTR) }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 64 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(ADDI, RRI_INSTR) }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 66 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(LW, RIR_INSTR) }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 67 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SW, RIR_INSTR) }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 68 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(LH, RIR_INSTR) }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 69 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(LHU, RIR_INSTR) }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 70 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SH, RIR_INSTR) }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 71 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(LB, RIR_INSTR) }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 72 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(LBU, RIR_INSTR) }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 73 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SB, RIR_INSTR) }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 74 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(LUI, RI_INSTR) }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 76 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(AND, RRR_INSTR) }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 77 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(OR, RRR_INSTR) }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 78 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(NOR, RRR_INSTR) }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 79 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(ANDI, RRI_INSTR) }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 80 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(ORI, RRI_INSTR) }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 81 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SLL, RRI_INSTR) }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 82 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SRL, RRI_INSTR) }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 84 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(BEQ, RRI_INSTR) }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 85 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(BNE, RRI_INSTR) }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 86 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SLT, RRR_INSTR) }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 87 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SLTU, RRR_INSTR) }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 88 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SLTI, RRI_INSTR) }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 89 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SLTIU, RRI_INSTR) }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 91 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(J, I_INSTR) }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 93 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_INSTRUCTION(SYSCALL, EMPTY_INSTR) }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 95 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{
	strncpy(yylval->string, mips_lexer_text, mips_lexer_leng);
	yylval->string[mips_lexer_leng] = '\0';
	return LABEL;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 101 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ sscanf(mips_lexer_text, "$%d", &yylval->integer); return REGISTER; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 102 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ sscanf(mips_lexer_text, "$r%d", &yylval->integer); return REGISTER; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(ZERO) }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(AT) }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(V0) }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(V1) }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(A0) }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(A1) }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(A2) }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(A3) }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T0) }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T1) }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T2) }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T3) }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T4) }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T5) }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T6) }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T7) }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T8) }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(T9) }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 122 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(S0) }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(S1) }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 124 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(S2) }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 125 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(S3) }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 126 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(S4) }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 127 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(S5) }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 128 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(S6) }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 129 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(S7) }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 130 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(K0) }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 131 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(K1) }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 132 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(GP) }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 133 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(SP) }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 134 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(FP) }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 135 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ RETURN_REGISTER(RA) }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 137 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ sscanf(mips_lexer_text, "%d", &yylval->integer); return INTEGER; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 139 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ sscanf(mips_lexer_text, "-0x%x", &yylval->integer); yylval->integer *= -1; return INTEGER; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 141 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ sscanf(mips_lexer_text, "0x%x", &yylval->integer); return INTEGER; }
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 143 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return NEWLINE; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 145 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ return *mips_lexer_text; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 147 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ BEGIN(READ_EOF_ONCE); return NEWLINE; }
	YY_BREAK
case YY_STATE_EOF(READ_EOF_ONCE):
#line 148 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
{ BEGIN(INITIAL); yyterminate(); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 150 "..\\..\\simulator\\flex_bison\\mips_lexer.l"
ECHO;
	YY_BREAK
#line 1308 "..\\..\\simulator\\flex_bison\\..\\mips_lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed mips_lexer_in at a new source and called
			 * mips_lexer_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = mips_lexer_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( mips_lexer_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * mips_lexer_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of mips_lexer_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					mips_lexer_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			mips_lexer_restart(mips_lexer_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) mips_lexer_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 151 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 151 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 150);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up mips_lexer_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					mips_lexer_restart(mips_lexer_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( mips_lexer_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve mips_lexer_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void mips_lexer_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        mips_lexer_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            mips_lexer__create_buffer(mips_lexer_in,YY_BUF_SIZE );
	}

	mips_lexer__init_buffer(YY_CURRENT_BUFFER,input_file );
	mips_lexer__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void mips_lexer__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		mips_lexer_pop_buffer_state();
	 *		mips_lexer_push_buffer_state(new_buffer);
     */
	mips_lexer_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	mips_lexer__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (mips_lexer_wrap()) processing, but the only time this flag
	 * is looked at is after mips_lexer_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void mips_lexer__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	mips_lexer_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE mips_lexer__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) mips_lexer_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mips_lexer__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) mips_lexer_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in mips_lexer__create_buffer()" );

	b->yy_is_our_buffer = 1;

	mips_lexer__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with mips_lexer__create_buffer()
 * 
 */
    void mips_lexer__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		mips_lexer_free((void *) b->yy_ch_buf  );

	mips_lexer_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a mips_lexer_restart() or at EOF.
 */
    static void mips_lexer__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	mips_lexer__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then mips_lexer__init_buffer was _probably_
     * called from mips_lexer_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void mips_lexer__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		mips_lexer__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void mips_lexer_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	mips_lexer_ensure_buffer_stack();

	/* This block is copied from mips_lexer__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from mips_lexer__switch_to_buffer. */
	mips_lexer__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void mips_lexer_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	mips_lexer__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		mips_lexer__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void mips_lexer_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)mips_lexer_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in mips_lexer_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)mips_lexer_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in mips_lexer_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE mips_lexer__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) mips_lexer_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mips_lexer__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	mips_lexer__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to mips_lexer_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       mips_lexer__scan_bytes() instead.
 */
YY_BUFFER_STATE mips_lexer__scan_string (yyconst char * yystr )
{
    
	return mips_lexer__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to mips_lexer_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE mips_lexer__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) mips_lexer_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in mips_lexer__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = mips_lexer__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in mips_lexer__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up mips_lexer_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		mips_lexer_text[mips_lexer_leng] = (yy_hold_char); \
		(yy_c_buf_p) = mips_lexer_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		mips_lexer_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int mips_lexer_get_lineno  (void)
{
        
    return mips_lexer_lineno;
}

/** Get the input stream.
 * 
 */
FILE *mips_lexer_get_in  (void)
{
        return mips_lexer_in;
}

/** Get the output stream.
 * 
 */
FILE *mips_lexer_get_out  (void)
{
        return mips_lexer_out;
}

/** Get the length of the current token.
 * 
 */
int mips_lexer_get_leng  (void)
{
        return mips_lexer_leng;
}

/** Get the current token.
 * 
 */

char *mips_lexer_get_text  (void)
{
        return mips_lexer_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void mips_lexer_set_lineno (int  line_number )
{
    
    mips_lexer_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see mips_lexer__switch_to_buffer
 */
void mips_lexer_set_in (FILE *  in_str )
{
        mips_lexer_in = in_str ;
}

void mips_lexer_set_out (FILE *  out_str )
{
        mips_lexer_out = out_str ;
}

int mips_lexer_get_debug  (void)
{
        return mips_lexer__flex_debug;
}

void mips_lexer_set_debug (int  bdebug )
{
        mips_lexer__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from mips_lexer_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    mips_lexer_in = stdin;
    mips_lexer_out = stdout;
#else
    mips_lexer_in = (FILE *) 0;
    mips_lexer_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * mips_lexer_lex_init()
     */
    return 0;
}

/* mips_lexer_lex_destroy is for both reentrant and non-reentrant scanners. */
int mips_lexer_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		mips_lexer__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		mips_lexer_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	mips_lexer_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * mips_lexer_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *mips_lexer_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *mips_lexer_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void mips_lexer_free (void * ptr )
{
	free( (char *) ptr );	/* see mips_lexer_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 150 "..\\..\\simulator\\flex_bison\\mips_lexer.l"


